---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ngsa-memory
  namespace: ngsa
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/app: glob:beta-*
spec:
  releaseName: ngsa-memory
  chart:
    git: git@github.com:retaildevcrews/ngsa
    path: gitops/charts/ngsa
    ref: main
  values:
    autoscaling:
      enabled: false
    app:
      args:
      - --in-memory
      - --prometheus
      - --zone
      - dev
      - --region
      - dev
      secretName: ngsa-secrets
      image:
        repository: ghcr.io/retaildevcrews/ngsa-app
        tag: beta-0.3.0-0328-0602-25
    cert:
      enabled: false
    ingress:
      hosts:
      - ngsa-mem-dev.cse.ms
      paths:
      - /
    gateway:
      name: wildcard-gateway
    podAnnotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: '/metrics'
      prometheus.io/port: '8080'
      prometheus.io/scheme: 'http'
      interval: '30s'
